version: 2.1
executors:
  go-docker:
    docker:
      - image: circleci/golang:1.21

jobs:
  build:
    executor: go-docker
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go build -v .
  deploy:
    executor: go-docker
    steps:
      - add_ssh_keys: # add key from CircleCI account
          fingerprints:
            - "XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX:XX"
      - run:
          name: Deploy Over SSH
          command: |
            ssh -v $SSH_USER@$SSH_HOST ./update-golang-app.sh
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master